@startuml
start
:User executes AddScheduleCommand;
:Parse input from user;
:Check for overlapping Schedule;

' Since the beta syntax does not support placing the condition outside the
' diamond we place it as the true branch instead.

if () then ([Overlapping Schedule is found])
    :Show error message to user;
    stop
else([else])
endif
:Add Schedule;
:Show feedback message to user;
stop
@enduml