@startuml
start
:User executes DeleteSessionCommand;
:Parse input from user;
:Check for associated Schedules;

' Since the beta syntax does not support placing the condition outside the
' diamond we place it as the true branch instead.

if () then ([No associated Schedules found])
else([else])
    if () then ([Force flag passed])
        :Delete Associated Schedules;
    else ([else])
        :Show error message to user;
        stop
    endif
endif
:Delete Session;
:Show feedback message to user;
stop
@enduml
