@startuml
start
:Edit Session Command;

if () then ([isUpdatingGym])
    :Update Gym;
    else ([else])
    endif

    if () then ([isUpdatingStartTime])
        :Update Start Time;
        :Duration;
        else ([else])
        endif
        :Print Successful;
stop
@enduml
