@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #5F0000
    FontName Arial
}

Package Client {
class Client
Class Address
Class Email
Class Name
Class Phone
}

Package Session {
Class Session
Class Gym
Class ExerciseType
Class Interval
}

Package Schedule {
Class Schedule
Class Remark
Class Weight
Class PaymentStatus
}

Package Tag {
Class Tag
}

Client *--> "*" Tag
Client *--> Name
Client *--> Phone
Client *--> Email
Client *--> Address

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

Schedule *--> Remark
Schedule *--> Weight
Schedule *--> PaymentStatus

Remark -[hidden]right-> Weight
Weight -[hidden]right-> PaymentStatus

Schedule -left-> "1" Client
Schedule -right-> "1" Session

Session *--> Gym
Session *--> ExerciseType
Session *--> Interval

Gym -[hidden]right-> ExerciseType
ExerciseType -[hidden]right-> Interval

@enduml
