@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #5F0000
    FontName Arial
}

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface CheckExisting <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>

Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs

Class "UniqueList<Client>" as UniqueList_client
Class "UniqueList<Session>" as UniqueList_session
Class "UniqueList<Schedule>" as UniqueList_schedule

Package Client {
class Client
}

Package Session {
Class Session
}

Package Schedule {
Class Schedule
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
Model .left.> ReadOnlyUserPrefs
ModelManager ---> "1" AddressBook
ModelManager --left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueList_client
UniqueList_client ---> "*" Client

AddressBook *--> "1" UniqueList_session
UniqueList_session ---> "*" Session

AddressBook *--> "1" UniqueList_schedule
UniqueList_schedule ---> "*" Schedule

Client ..|> CheckExisting
Schedule ..|> CheckExisting
Session ..|> CheckExisting

Schedule --> "1" Client
Schedule --> "1" Session

ModelManager ---> Client : has filterable list of >
ModelManager ---> Schedule : has filterable list of >
ModelManager ---> Session : has filterable list of >
@enduml
